 "twitter":
    "consumer_key": "Twitter Consumer Key to be given"
    "consumer_secret": "Twitter Consumer Key to be given"
    "access_token": "Twitter Consumer Key to be given"
    "access_token_secret": "Twitter Consumer Key to be given"
